### ISSUE TITLE
Environment Variable Safety

### ISSUE THREAD

**Issue by phudv96** [phudv96/Intern-Projects#1]
On app.js file
`await connectDB(process.env.MONGO_URI)//MONGO_URI=mongodb+srv://hiep:Cfvip113@todolist.el6f55x.mongodb.net/`

Ensure that process.env.MONGO_URI is not hard-coded and is securely stored in a .env file.
Suggestion: Remove the hard-coded URL in the comment to avoid potential security risks.

**Comment by Ikariius** [comment]
Should I push my .env file to the repo if that is the case ? Because otherwise I wouldn't be able to give you my mongoDB URL for establishing connection
